import { CanvasStarterData } from "./types/CanvasInterfaces";

export const CanvasStarters: CanvasStarterData[] = [
    {
        "name": "Service Estimate",
        "canvasDesign": {
            "Shapes": [
                {
                    "id": "iycU",
                    "type": "Heading",
                    "x": 539,
                    "y": 55,
                    "rotation": 0,
                    "textValue": "LICENSE #XXXXXX",
                    "fontSize": 28,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "bold",
                    "textDecoration": ""
                },
                {
                    "id": "y3NL",
                    "type": "Heading",
                    "x": 375,
                    "y": 107,
                    "rotation": 0,
                    "textValue": "Client",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": ""
                },
                {
                    "id": "VNLq",
                    "type": "ShortTextInput",
                    "name": "Client Name",
                    "x": 445,
                    "y": 107,
                    "rotation": 0,
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "textValue": "John Doe",
                    "horizontalAlign": "left",
                    "width": 331,
                    "height": 20,
                },
                {
                    "id": "X6FS",
                    "type": "Heading",
                    "x": 354,
                    "y": 137,
                    "rotation": 0,
                    "textValue": "Address",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": ""
                },
                {
                    "id": "wUD6",
                    "type": "ShortTextInput",
                    "name": "Client Address",
                    "x": 445,
                    "y": 137,
                    "rotation": 0,
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "textValue": "1234 W 1st St Los Angeles, CA",
                    "horizontalAlign": "left",
                    "width": 332,
                    "height": 20,
                },
                {
                    "id": "XsXu",
                    "type": "Heading",
                    "x": 369,
                    "y": 167,
                    "rotation": 0,
                    "textValue": "Phone",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": ""
                },
                {
                    "id": "GutW",
                    "type": "PhoneInput",
                    "name": "Phone Number",
                    "x": 446,
                    "y": 166,
                    "rotation": 0,
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "textValue": "(555)555-5555",
                    "horizontalAlign": "left",
                    "width": 160,
                    "height": 20,
                },
                {
                    "id": "TFIW",
                    "type": "EmailInput",
                    "name": "Email Address",
                    "x": 446,
                    "y": 196,
                    "rotation": 0,
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "textValue": "john.doe@email.com",
                    "horizontalAlign": "left",
                    "width": 334,
                    "height": 20,
                },
                {
                    "id": "QAI8",
                    "type": "Heading",
                    "x": 376,
                    "y": 196,
                    "rotation": 0,
                    "textValue": "Email",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": ""
                },
                {
                    "id": "PhkT",
                    "type": "Heading",
                    "x": 25,
                    "y": 137,
                    "rotation": 0,
                    "textValue": "Licensed Bonded Insured",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal bold",
                    "textDecoration": ""
                },
                {
                    "id": "kBEX",
                    "type": "Heading",
                    "x": 23,
                    "y": 166,
                    "rotation": 0,
                    "textValue": "(555)555-5555",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": ""
                },
                {
                    "id": "cEAh",
                    "type": "Heading",
                    "x": 25,
                    "y": 196,
                    "rotation": 0,
                    "textValue": "johndoe@mybizemail.com",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": ""
                },
                {
                    "id": "aMrS",
                    "type": "Heading",
                    "x": 28,
                    "y": 860,
                    "rotation": 0,
                    "textValue": "Notes:",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": ""
                },
                {
                    "id": "Cdz2",
                    "type": "LongTextInput",
                    "name": "Notes",
                    "x": 29,
                    "y": 893,
                    "rotation": 0,
                    "verticalAlign": "top",
                    "fontSize": 18,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "textValue": "",
                    "horizontalAlign": "left",
                    "width": 754,
                    "height": 122,
                },
                {
                    "id": "XzPU",
                    "type": "Heading",
                    "x": 23,
                    "y": 244,
                    "rotation": 0,
                    "textValue": "Service Estimate",
                    "fontSize": 28,
                    "fill": "#848484",
                    "fontFamily": "Arial",
                    "fontStyle": "bold",
                    "textDecoration": ""
                },
                {
                    "id": "3F80",
                    "type": "Rectangle",
                    "x": 13,
                    "y": 278,
                    "rotation": 0,
                    "width": 786,
                    "height": 6,
                    "fill": "#bfbfbf",
                    "stroke": "",
                    "strokeWidth": 1
                },
                {
                    "id": "aULg",
                    "name": "Table",
                    "type": "TableInput",
                    "x": 25,
                    "y": 293,
                    "rotation": 0,
                    "border": undefined,
                    "rows": [
                        [
                            {
                                "id": "1jFr",
                                "x": 100,
                                "y": 100,
                                "width": 601,
                                "height": 31,
                                "verticalAlign": "middle",
                                "horizontalAlign": "left",
                                "type": "TableCell",
                                "content": {
                                    "id": "1jFr",
                                    "type": "TextCell",
                                    "x": 0,
                                    "y": 0,
                                    "rotation": 0,
                                    "textValue": "Service Description",
                                    "fontSize": 20,
                                    "fill": "black",
                                    "fontFamily": "Arial",
                                    "fontStyle": "bold",
                                    "textDecoration": "none"
                                },
                                "rotation": 0
                            },
                            {
                                "id": "jyfT",
                                "x": 200,
                                "y": 100,
                                "width": 156.138671875,
                                "height": 31,
                                "verticalAlign": "middle",
                                "horizontalAlign": "center",
                                "type": "TableCell",
                                "content": {
                                    "id": "jyfT",
                                    "type": "TextCell",
                                    "x": 601,
                                    "y": 0,
                                    "rotation": 0,
                                    "textValue": "Cost",
                                    "fontSize": 20,
                                    "fill": "black",
                                    "fontFamily": "Arial",
                                    "fontStyle": "bold",
                                    "textDecoration": "none"
                                },
                                "rotation": 0
                            }
                        ],
                        [
                            {
                                "id": "qwbm",
                                "x": 100,
                                "y": 150,
                                "width": 601,
                                "height": 91,
                                "verticalAlign": "middle",
                                "horizontalAlign": "left",
                                "type": "TableCell",
                                "content": {
                                    "id": "qwbm",
                                    "x": 0,
                                    "y": 31,
                                    "textValue": "",
                                    "fontSize": 20,
                                    "fill": "black",
                                    "fontFamily": "Arial",
                                    "fontStyle": "normal",
                                    "textDecoration": "none",
                                    "rotation": 0,
                                    "type": "CellInput"
                                },
                                "rotation": 0
                            },
                            {
                                "id": "C5Ep",
                                "x": 200,
                                "y": 150,
                                "width": 156.138671875,
                                "height": 91,
                                "verticalAlign": "middle",
                                "horizontalAlign": "center",
                                "type": "TableCell",
                                "content": {
                                    "id": "C5Ep",
                                    "x": 601,
                                    "y": 31,
                                    "textValue": "",
                                    "fontSize": 20,
                                    "fill": "black",
                                    "fontFamily": "Arial",
                                    "fontStyle": "normal",
                                    "textDecoration": "none",
                                    "rotation": 0,
                                    "type": "CellInput"
                                },
                                "rotation": 0
                            }
                        ],
                        [
                            {
                                "id": "pJ42",
                                "x": 100,
                                "y": 150,
                                "width": 601,
                                "height": 91,
                                "verticalAlign": "middle",
                                "horizontalAlign": "left",
                                "type": "TableCell",
                                "content": {
                                    "id": "pJ42",
                                    "x": 0,
                                    "y": 122,
                                    "textValue": "",
                                    "fontSize": 20,
                                    "fill": "black",
                                    "fontFamily": "Arial",
                                    "fontStyle": "normal",
                                    "textDecoration": "none",
                                    "rotation": 0,
                                    "type": "CellInput"
                                },
                                "rotation": 0
                            },
                            {
                                "id": "votn",
                                "x": 200,
                                "y": 150,
                                "width": 156.138671875,
                                "height": 91,
                                "verticalAlign": "middle",
                                "horizontalAlign": "center",
                                "type": "TableCell",
                                "content": {
                                    "id": "votn",
                                    "x": 601,
                                    "y": 122,
                                    "textValue": "",
                                    "fontSize": 20,
                                    "fill": "black",
                                    "fontFamily": "Arial",
                                    "fontStyle": "normal",
                                    "textDecoration": "none",
                                    "rotation": 0,
                                    "type": "CellInput"
                                },
                                "rotation": 0
                            }
                        ],
                        [
                            {
                                "id": "21FD",
                                "x": 100,
                                "y": 150,
                                "width": 601,
                                "height": 91,
                                "verticalAlign": "middle",
                                "horizontalAlign": "left",
                                "type": "TableCell",
                                "content": {
                                    "id": "21FD",
                                    "x": 0,
                                    "y": 213,
                                    "textValue": "",
                                    "fontSize": 20,
                                    "fill": "black",
                                    "fontFamily": "Arial",
                                    "fontStyle": "normal",
                                    "textDecoration": "none",
                                    "rotation": 0,
                                    "type": "CellInput"
                                },
                                "rotation": 0
                            },
                            {
                                "id": "KRNt",
                                "x": 200,
                                "y": 150,
                                "width": 156.138671875,
                                "height": 91,
                                "verticalAlign": "middle",
                                "horizontalAlign": "center",
                                "type": "TableCell",
                                "content": {
                                    "id": "KRNt",
                                    "x": 601,
                                    "y": 213,
                                    "textValue": "",
                                    "fontSize": 20,
                                    "fill": "black",
                                    "fontFamily": "Arial",
                                    "fontStyle": "normal",
                                    "textDecoration": "none",
                                    "rotation": 0,
                                    "type": "CellInput"
                                },
                                "rotation": 0
                            }
                        ],
                        [
                            {
                                "id": "urmm",
                                "x": 100,
                                "y": 150,
                                "width": 601,
                                "height": 91,
                                "verticalAlign": "middle",
                                "horizontalAlign": "left",
                                "type": "TableCell",
                                "content": {
                                    "id": "urmm",
                                    "x": 0,
                                    "y": 304,
                                    "textValue": "",
                                    "fontSize": 20,
                                    "fill": "black",
                                    "fontFamily": "Arial",
                                    "fontStyle": "normal",
                                    "textDecoration": "none",
                                    "rotation": 0,
                                    "type": "CellInput"
                                },
                                "rotation": 0
                            },
                            {
                                "id": "pGI6",
                                "x": 200,
                                "y": 150,
                                "width": 156.138671875,
                                "height": 91,
                                "verticalAlign": "middle",
                                "horizontalAlign": "center",
                                "type": "TableCell",
                                "content": {
                                    "id": "pGI6",
                                    "x": 601,
                                    "y": 304,
                                    "textValue": "",
                                    "fontSize": 20,
                                    "fill": "black",
                                    "fontFamily": "Arial",
                                    "fontStyle": "normal",
                                    "textDecoration": "none",
                                    "rotation": 0,
                                    "type": "CellInput"
                                },
                                "rotation": 0
                            }
                        ],
                        [
                            {
                                "id": "Ce4C",
                                "x": 100,
                                "y": 150,
                                "width": 601,
                                "height": 91,
                                "verticalAlign": "middle",
                                "horizontalAlign": "left",
                                "type": "TableCell",
                                "content": {
                                    "id": "Ce4C",
                                    "x": 0,
                                    "y": 395,
                                    "textValue": "",
                                    "fontSize": 20,
                                    "fill": "black",
                                    "fontFamily": "Arial",
                                    "fontStyle": "normal",
                                    "textDecoration": "none",
                                    "rotation": 0,
                                    "type": "CellInput"
                                },
                                "rotation": 0
                            },
                            {
                                "id": "5UPJ",
                                "x": 200,
                                "y": 150,
                                "width": 156.138671875,
                                "height": 91,
                                "verticalAlign": "middle",
                                "horizontalAlign": "center",
                                "type": "TableCell",
                                "content": {
                                    "id": "5UPJ",
                                    "x": 601,
                                    "y": 395,
                                    "textValue": "",
                                    "fontSize": 20,
                                    "fill": "black",
                                    "fontFamily": "Arial",
                                    "fontStyle": "normal",
                                    "textDecoration": "none",
                                    "rotation": 0,
                                    "type": "CellInput"
                                },
                                "rotation": 0
                            }
                        ]
                    ]
                },
                {
                    "id": "en4h",
                    "type": "Rectangle",
                    "x": 28,
                    "y": 785,
                    "rotation": 0,
                    "width": 754,
                    "height": 59,
                    "fill": "#bfbfbf",
                    "stroke": "",
                    "strokeWidth": 1
                },
                {
                    "id": "95Kb",
                    "type": "Heading",
                    "x": 42,
                    "y": 801,
                    "rotation": 0,
                    "textValue": "TOTAL MATERIALS & LABOR",
                    "fontSize": 28,
                    "fill": "#ffffff",
                    "fontFamily": "Arial",
                    "fontStyle": "bold",
                    "textDecoration": ""
                },
                {
                    "id": "el2w",
                    "type": "ShortTextInput",
                    "name": "Total Cost",
                    "x": 634,
                    "y": 801,
                    "rotation": 0,
                    "fontSize": 28,
                    "fill": "#ffffff",
                    "fontFamily": "Arial",
                    "fontStyle": "normal bold",
                    "textDecoration": "",
                    "textValue": "",
                    "horizontalAlign": "center",
                    "width": 142,
                    "height": 28
                },
                {
                    "id": "yNBE",
                    "type": "UserImage",
                    "x": 25,
                    "y": 25,
                    "rotation": 0,
                    "src": "https://bryxstorage.blob.core.windows.net/assets/bryx_logo.png",
                    "width": 80,
                    "height": 80
                }
            ],
            "inputOrder": [
                "VNLq",
                "wUD6",
                "GutW",
                "TFIW",
                "aULg",
                "el2w",
                "Cdz2"
            ],
            "pageWidth": 8.5,
            "pageHeight": 11
        }
    },
    {
        name: "Packages Estimate",
        "canvasDesign": {
            "Shapes": [
                {
                    "id": "9gbG",
                    "type": "RoundedRectangle",
                    "x": 24,
                    "y": 240,
                    "rotation": 0,
                    "width": 751,
                    "height": 195,
                    "fill": "transparent",
                    "stroke": "#000000",
                    "strokeWidth": 3,
                    "cornerRadius": 20
                },
                {
                    "id": "iycU",
                    "type": "Heading",
                    "x": 539,
                    "y": 55,
                    "rotation": 0,
                    "textValue": "LICENSE #XXXXXX",
                    "fontSize": 28,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "bold",
                    "textDecoration": ""
                },
                {
                    "id": "y3NL",
                    "type": "Heading",
                    "x": 375,
                    "y": 107,
                    "rotation": 0,
                    "textValue": "Client",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": ""
                },
                {
                    "id": "VNLq",
                    "type": "ShortTextInput",
                    "name": "Client Name",
                    "x": 445,
                    "y": 107,
                    "rotation": 0,
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "textValue": "John Doe",
                    "horizontalAlign": "left",
                    "width": 331,
                    "height": 20,
                },
                {
                    "id": "X6FS",
                    "type": "Heading",
                    "x": 354,
                    "y": 137,
                    "rotation": 0,
                    "textValue": "Address",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": ""
                },
                {
                    "id": "wUD6",
                    "type": "ShortTextInput",
                    "name": "Client Address",
                    "x": 445,
                    "y": 137,
                    "rotation": 0,
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "textValue": "1234 W 1st St Los Angeles, CA",
                    "horizontalAlign": "left",
                    "width": 332,
                    "height": 20,
                },
                {
                    "id": "XsXu",
                    "type": "Heading",
                    "x": 369,
                    "y": 167,
                    "rotation": 0,
                    "textValue": "Phone",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": ""
                },
                {
                    "id": "GutW",
                    "type": "PhoneInput",
                    "name": "Phone Number",
                    "x": 446,
                    "y": 166,
                    "rotation": 0,
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "textValue": "(555)555-5555",
                    "horizontalAlign": "left",
                    "width": 160,
                    "height": 20,
                },
                {
                    "id": "TFIW",
                    "type": "EmailInput",
                    "name": "Email Address",
                    "x": 446,
                    "y": 196,
                    "rotation": 0,
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "textValue": "john.doe@email.com",
                    "horizontalAlign": "left",
                    "width": 334,
                    "height": 20,
                },
                {
                    "id": "QAI8",
                    "type": "Heading",
                    "x": 376,
                    "y": 196,
                    "rotation": 0,
                    "textValue": "Email",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": ""
                },
                {
                    "id": "jv0z",
                    "type": "UserImage",
                    "x": 25,
                    "y": 25,
                    "rotation": 0,
                    "src": "https://bryxstorage.blob.core.windows.net/assets/bryx_logo.png",
                    "width": 80,
                    "height": 80
                },
                {
                    "id": "PhkT",
                    "type": "Heading",
                    "x": 25,
                    "y": 137,
                    "rotation": 0,
                    "textValue": "Licensed Bonded Insured",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal bold",
                    "textDecoration": ""
                },
                {
                    "id": "kBEX",
                    "type": "Heading",
                    "x": 23,
                    "y": 166,
                    "rotation": 0,
                    "textValue": "(623)469-5513",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": ""
                },
                {
                    "id": "cEAh",
                    "type": "Heading",
                    "x": 25,
                    "y": 196,
                    "rotation": 0,
                    "textValue": "johndoe@mybizemail.com",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": ""
                },
                {
                    "id": "TjCD",
                    "type": "Paragraph",
                    "x": 34,
                    "y": 282,
                    "rotation": 0,
                    "textValue": "SITE PREPARATION - Base of area and workspaces are cleared of all debris & obstacles\nCLEAN - Work area is cleaned to ensure a safe and efficient work environment.\nPROTECTION - Mask & tape all areas not to be affected including windows and fixtures. \nREPAIR - Minor repairs within scope of work. \nWORK AREA - Ensure proper preparation of work area. \nMATERIALS - Use of high-quality materials and tools. \nPERMITS - Expedite necessary permits if applicable.\nWARRANTY - 2 Year Limited Warranty",
                    "fontSize": 18,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal bold",
                    "textDecoration": "",
                    "horizontalAlign": "left"
                },
                {
                    "id": "PLOJ",
                    "type": "Heading",
                    "x": 34,
                    "y": 251,
                    "rotation": 0,
                    "textValue": "INCLUDED IN ALL PACKAGES",
                    "fontSize": 24,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "bold",
                    "textDecoration": ""
                },
                {
                    "id": "rZu9",
                    "type": "Heading",
                    "x": 34,
                    "y": 451,
                    "rotation": 0,
                    "textValue": "PACKAGES",
                    "fontSize": 24,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "bold",
                    "textDecoration": ""
                },
                {
                    "id": "0WFV",
                    "type": "RoundedRectangle",
                    "x": 540,
                    "y": 485,
                    "rotation": 0,
                    "width": 238,
                    "height": 328,
                    "fill": "#FC4C02",
                    "stroke": "",
                    "strokeWidth": 1,
                    "cornerRadius": 20
                },
                {
                    "id": "eRiz",
                    "type": "RoundedRectangle",
                    "x": 288,
                    "y": 485,
                    "rotation": 0,
                    "width": 238,
                    "height": 328,
                    "fill": "#005778",
                    "stroke": "",
                    "strokeWidth": 1,
                    "cornerRadius": 20
                },
                {
                    "id": "3Sm9",
                    "type": "RoundedRectangle",
                    "x": 32,
                    "y": 485,
                    "rotation": 0,
                    "width": 238,
                    "height": 328,
                    "fill": "#008E97",
                    "stroke": "",
                    "strokeWidth": 1,
                    "cornerRadius": 20
                },
                {
                    "id": "bWEj",
                    "type": "RoundedRectangle",
                    "x": 33,
                    "y": 825,
                    "rotation": 0,
                    "width": 750,
                    "height": 205,
                    "fill": "transparent",
                    "stroke": "#000000",
                    "strokeWidth": 3,
                    "cornerRadius": 20
                },
                {
                    "id": "aMrS",
                    "type": "Heading",
                    "x": 44,
                    "y": 834,
                    "rotation": 0,
                    "textValue": "Notes:",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": ""
                },
                {
                    "id": "Cdz2",
                    "type": "LongTextInput",
                    "name": "Notes",
                    "x": 44,
                    "y": 860,
                    "rotation": 0,
                    "verticalAlign": "top",
                    "fontSize": 18,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "textValue": "",
                    "horizontalAlign": "left",
                    "width": 729,
                    "height": 157,
                },
                {
                    "id": "LbwH",
                    "type": "Heading",
                    "x": 100,
                    "y": 495,
                    "rotation": 0,
                    "textValue": "DELUXE",
                    "fontSize": 24,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "bold",
                    "textDecoration": ""
                },
                {
                    "id": "K9KX",
                    "type": "Heading",
                    "x": 349,
                    "y": 495,
                    "rotation": 0,
                    "textValue": "ULTIMATE",
                    "fontSize": 24,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "bold",
                    "textDecoration": ""
                },
                {
                    "id": "IUxP",
                    "type": "Heading",
                    "x": 601,
                    "y": 495,
                    "rotation": 0,
                    "textValue": "MAXIMUM",
                    "fontSize": 24,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "bold",
                    "textDecoration": ""
                },
                {
                    "id": "LLbh",
                    "type": "Paragraph",
                    "x": 38,
                    "y": 533,
                    "rotation": 0,
                    "textValue": "Sherwin Williams \nSuper Paint \nOR\nDunn Edwards \nVersaFlat\n\nExpected Life of Paint: \n3-5 Years\n\n\nTotal Materials & Labor:",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal bold",
                    "textDecoration": "",
                    "horizontalAlign": "center"
                },
                {
                    "id": "POVQ",
                    "type": "Paragraph",
                    "x": 293,
                    "y": 528,
                    "rotation": 0,
                    "textValue": "Sherwin Williams \nLatitude\nOR\nDunn Edwards \nSpartaShield\n\nExpected Life of Paint: \n5-7 Years\n\n\nTotal Materials & Labor:",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal bold",
                    "textDecoration": "",
                    "horizontalAlign": "center"
                },
                {
                    "id": "T3OU",
                    "type": "Paragraph",
                    "x": 547,
                    "y": 528,
                    "rotation": 0,
                    "textValue": "Sherwin Williams \nDuration\nOR\nDunn Edwards \nEverShield\n\nExpected Life of Paint: \n7-10 Years\n\n\nTotal Materials & Labor:",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal bold",
                    "textDecoration": "",
                    "horizontalAlign": "center"
                },
                {
                    "id": "mYUa",
                    "type": "ShortTextInput",
                    "name": "Ultimate Price",
                    "x": 299,
                    "y": 768,
                    "rotation": 0,
                    "fontSize": 28,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal bold",
                    "textDecoration": "",
                    "textValue": "$0.00",
                    "horizontalAlign": "center",
                    "width": 219,
                    "height": 28,
                },
                {
                    "id": "9oOp",
                    "type": "ShortTextInput",
                    "name": "Deluxe Price",
                    "x": 42,
                    "y": 768,
                    "rotation": 0,
                    "fontSize": 28,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal bold",
                    "textDecoration": "",
                    "textValue": "$0.00",
                    "horizontalAlign": "center",
                    "width": 219,
                    "height": 28,
                },
                {
                    "id": "zjou",
                    "type": "ShortTextInput",
                    "name": "Maximum Price",
                    "x": 551,
                    "y": 768,
                    "rotation": 0,
                    "fontSize": 28,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal bold",
                    "textDecoration": "",
                    "textValue": "$0.00",
                    "horizontalAlign": "center",
                    "width": 218,
                    "height": 28,
                }
            ],
            "inputOrder": [
                "VNLq",
                "wUD6",
                "GutW",
                "TFIW",
                "9oOp",
                "mYUa",
                "zjou",
                "Cdz2"
            ],
            "pageWidth": 8.5,
            "pageHeight": 11
        },
    }
]