import { CanvasStarterData } from "./types/CanvasInterfaces";

export const CanvasStarters: CanvasStarterData[] = [
    {
        "name": "Two Packages",
        "canvasDesign": {
            "Shapes": [
                {
                    "id": "image-2ivF",
                    "type": "Image",
                    "x": -82.00102623051185,
                    "y": -33.00090789941839,
                    "rotation": 0,
                    "src": "https://images.unsplash.com/photo-1598103586054-c4b456cbddc4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=Mnw0Mjk3NTV8MHwxfHNlYXJjaHwxfHxicnVzaHxlbnwwfHx8fDE2ODEwOTc0NDE&ixlib=rb-4.0.3&q=80&w=400",
                    "width": 1003.4034919273676,
                    "height": 247.05160737552552,
                    "isDragging": false
                },
                {
                    "id": "text-field-dstD",
                    "type": "TextField",
                    "x": 157.7248393703008,
                    "y": 52.71530477007167,
                    "rotation": 0.2729540441292761,
                    "value": "Bryx Painting",
                    "fontSize": 72,
                    "fill": "#ffffff",
                    "fontFamily": "Verdana",
                    "fontStyle": "bold",
                    "textDecoration": "",
                    "isDragging": false,
                },
                {
                    "id": "text-field-3eL9",
                    "type": "TextField",
                    "x": 44.99923975168216,
                    "y": 229.99951772900764,
                    "rotation": 0,
                    "value": "Client",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-field-oTVu",
                    "type": "TextField",
                    "x": 641.0004879830801,
                    "y": 195.99946270480035,
                    "rotation": 0,
                    "value": "License #9876",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "rectangle-APmy",
                    "type": "Rectangle",
                    "x": 61.999275355597646,
                    "y": 286.9996099754717,
                    "rotation": 0,
                    "width": 308.4075929920682,
                    "height": 229.11098518388167,
                    "fill": "#15a1ce",
                    "isDragging": false
                },
                {
                    "id": "rectangle-TiyI",
                    "type": "Rectangle",
                    "x": 419.38269793837395,
                    "y": 283.9996051203945,
                    "rotation": 0,
                    "width": 336.25618993176045,
                    "height": 232.8838005322078,
                    "fill": "#1571ce",
                    "isDragging": false
                },
                {
                    "id": "text-input-RJNx",
                    "type": "TextInput",
                    "format": "text",
                    "x": 112.999382167345,
                    "y": 227.99950801885348,
                    "rotation": 0,
                    "displayName": "Client Name",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-field-70Lv",
                    "type": "TextField",
                    "x": 86.99932771429738,
                    "y": 308.9996455793714,
                    "rotation": 0,
                    "value": "Basic Package",
                    "fontSize": 32,
                    "fill": "#ffffff",
                    "fontFamily": "Verdana",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-field-bmJX",
                    "type": "TextField",
                    "x": 456.00010052870334,
                    "y": 310.9996488160895,
                    "rotation": 0,
                    "value": "Premier Package",
                    "fontSize": 32,
                    "fill": "#ffffff",
                    "fontFamily": "Verdana",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-field-NY3z",
                    "type": "TextField",
                    "x": 88.99933190299342,
                    "y": 370.9997459176315,
                    "rotation": 0,
                    "value": "High Quality Paint\n\n2 Year Warranty",
                    "fontSize": 20,
                    "fill": "#ffffff",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-field-8ezI",
                    "type": "TextField",
                    "x": 457.0001026230512,
                    "y": 370.99974591763157,
                    "rotation": 0,
                    "value": "Best Quality Paint \n\n5 Year Warranty",
                    "fontSize": 20,
                    "fill": "#ffffff",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-input-sZ2I",
                    "type": "TextInput",
                    "format": "currency",
                    "x": 102.99936122386515,
                    "y": 452.9998786230724,
                    "rotation": 0,
                    "displayName": "Basic Package Price",
                    "fontSize": 20,
                    "fill": "#ffffff",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-input-uU4A",
                    "type": "TextInput",
                    "format": "currency",
                    "x": 486.0001633591426,
                    "y": 454.99988185979043,
                    "rotation": 0,
                    "displayName": "Premier Package Price",
                    "fontSize": 20,
                    "fill": "#ffffff",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                }
            ],
            "selectedId": "",
            "pageHeight": 11,
            "pageWidth": 8.5
        }
    },
    {
        "name": "List of Services",
        "canvasDesign": {
            "Shapes": [
                {
                    "id": "text-field-8waz",
                    "type": "TextField",
                    "x": 17,
                    "y": 32,
                    "rotation": 0,
                    "value": "Rockets Grooming",
                    "fontSize": 72,
                    "fill": "black",
                    "fontFamily": "Verdana",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "image-4tw0",
                    "type": "Image",
                    "x": 558.2196549054083,
                    "y": 127.99999999999991,
                    "rotation": 0,
                    "src": "https://images.unsplash.com/photo-1597595735781-6a57fb8e3e3d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0Mjk3NTV8MHwxfHNlYXJjaHwxfHxkb2clMjBiYXRofGVufDB8fHx8MTY4NTY0NTU1N3ww&ixlib=rb-4.0.3&q=80&w=400",
                    "width": 179.44701176125818,
                    "height": 269.17051764188716,
                    "isDragging": false
                },
                {
                    "id": "text-field-FOSG",
                    "type": "TextField",
                    "x": 30,
                    "y": 143,
                    "rotation": 0,
                    "value": "Owner Name",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-field-jmLp",
                    "type": "TextField",
                    "x": 31,
                    "y": 275,
                    "rotation": 0,
                    "value": "Pet Name",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-field-fO0w",
                    "type": "TextField",
                    "x": 18,
                    "y": 483,
                    "rotation": 0,
                    "value": "Services",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-field-EqoR",
                    "type": "TextField",
                    "x": 30,
                    "y": 207,
                    "rotation": 0,
                    "value": "Owner Phone",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "rectangle-7423",
                    "type": "Rectangle",
                    "x": -8.000000000000455,
                    "y": 410.0000000000005,
                    "rotation": 0,
                    "width": 867.4935756991505,
                    "height": 42.461504233367194,
                    "fill": "#ffb500",
                    "isDragging": false
                },
                {
                    "id": "text-input-Kzw2",
                    "type": "TextInput",
                    "format": "text",
                    "x": 174,
                    "y": 140,
                    "rotation": 0,
                    "displayName": "Pet Owner Name",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-input-UJL1",
                    "type": "TextInput",
                    "format": "phone",
                    "x": 173,
                    "y": 196,
                    "rotation": 0,
                    "displayName": "Pet Owner Phone",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-input-61N8",
                    "type": "TextInput",
                    "format": "text",
                    "x": 173,
                    "y": 260,
                    "rotation": 0,
                    "displayName": "Pet Name",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-input-fZDV",
                    "type": "TextInput",
                    "format": "paragraph",
                    "x": 14,
                    "y": 521,
                    "rotation": 0,
                    "displayName": "Services List",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-field-d5dg",
                    "type": "TextField",
                    "x": 501,
                    "y": 987,
                    "rotation": 0,
                    "value": "Total",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-input-Y03p",
                    "type": "TextInput",
                    "format": "currency",
                    "x": 571,
                    "y": 982,
                    "rotation": 0,
                    "displayName": "Total Price",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                }
            ],
            "selectedId": null,
            "pageHeight": 11,
            "pageWidth": 8.5
        }
    },
    {
        "name": "Set Options",
        "canvasDesign": {
            "Shapes": [
                {
                    "id": "rectangle-BXSx",
                    "type": "Rectangle",
                    "x": 347.84532557917174,
                    "y": 16,
                    "rotation": 0,
                    "width": 425.1546744208283,
                    "height": 102.70590449491907,
                    "fill": "#007f33",
                    "isDragging": false
                },
                {
                    "id": "text-field-VUJw",
                    "type": "TextField",
                    "x": 394,
                    "y": 36,
                    "rotation": 0,
                    "value": "Pest Control",
                    "fontSize": 64,
                    "fill": "#ffffff",
                    "fontFamily": "Times New Roman",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-field-JYeA",
                    "type": "TextField",
                    "x": 30,
                    "y": 208,
                    "rotation": 0,
                    "value": "Home Interior",
                    "fontSize": 28,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-field-zcEy",
                    "type": "TextField",
                    "x": 36,
                    "y": 246,
                    "rotation": 0,
                    "value": "- Thorough inspection to identify the infestation type and extent\n- Customized treatment plan using safe and eco-friendly solutions\n- Skilled technicians implement the treatment effectively and minimize risks\n- Ongoing support and maintenance for long-term pest prevention\n- Transform your home into a pest-free haven with our trusted process",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-field-rUwn",
                    "type": "TextField",
                    "x": 466,
                    "y": 387,
                    "rotation": 0,
                    "value": "Price ",
                    "fontSize": 24,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "bold",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-input-auH4",
                    "type": "TextInput",
                    "format": "currency",
                    "x": 545,
                    "y": 380,
                    "rotation": 0,
                    "displayName": "Interior Price",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-field-GIAt",
                    "type": "TextField",
                    "x": 33,
                    "y": 459,
                    "rotation": 0,
                    "value": "Home Exterior ",
                    "fontSize": 24,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-field-YxvY",
                    "type": "TextField",
                    "x": 29,
                    "y": 495,
                    "rotation": 0,
                    "value": "- Thorough inspection to identify the infestation type and extent\n- Customized treatment plan using safe and eco-friendly solutions\n- Skilled technicians implement the treatment effectively and minimize risks\n- Ongoing support and maintenance for long-term pest prevention\n- Transform your home into a pest-free haven with our trusted process",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-field-FJ3y",
                    "type": "TextField",
                    "x": 460,
                    "y": 651,
                    "rotation": 0,
                    "value": "Price",
                    "fontSize": 24,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "bold",
                    "textDecoration": "",
                    "isDragging": false
                },
                {
                    "id": "text-input-t6PF",
                    "type": "TextInput",
                    "format": "currency",
                    "x": 539,
                    "y": 645,
                    "rotation": 0,
                    "displayName": "Exterior Price",
                    "fontSize": 20,
                    "fill": "black",
                    "fontFamily": "Arial",
                    "fontStyle": "normal",
                    "textDecoration": "",
                    "isDragging": false
                }
            ],
            "selectedId": null,
            "pageHeight": 11,
            "pageWidth": 8.5
        },
    }

];